project: ./mri_to_ct/
mode: val
train:
  output_dir: /mnt/homeGPU/tenayat/mri_to_ct/24_11_19_baseline_400epoch
  batch_size: 1
  cuda: true
  mixed_precision: false
  opt_level: O1
  logging:
    freq: 10
    multi_modality_split: null
    tensorboard: true
    wandb: null
    image_window: null
  dataset:
    _target_: project.datasets.train_dataset.SynthRAD2023TrainDataset
    root: /mnt/homeGPU/tenayat/data/TRAIN
    num_workers: 0
    pin_memory: true
    patch_size:
    - 32
    - 160
    - 160
    focal_region_proportion: 0.0
    augmentation: false
    unpaired: true
  checkpointing:
    load_iter: null
    freq: 2420
    start_after: 0
    load_optimizers: true
  n_iters: 48400
  n_iters_decay: 12100
  gan:
    _target_: ganslate.nn.gans.unpaired.CycleGAN
    norm_type: instance
    weight_init_type: normal
    weight_init_gain: 0.02
    optimizer:
      adversarial_loss_type: lsgan
      beta1: 0.5
      beta2: 0.999
      lr_D: 0.0002
      lr_G: 0.0004
      lambda_AB: 5.0
      lambda_BA: 5.0
      lambda_identity: 0.0
      proportion_ssim: 0.0
    generator:
      _target_: ganslate.nn.generators.Vnet3D
      in_out_channels:
        AB:
        - 1
        - 1
        BA: ${train.gan.generator.in_out_channels.AB}
      use_memory_saving: false
      use_inverse: false
      first_layer_channels: 16
      down_blocks:
      - 2
      - 2
      - 3
      up_blocks:
      - 3
      - 3
      - 3
      is_separable: false
    discriminator:
      _target_: ganslate.nn.discriminators.PatchGAN3D
      in_channels:
        B: 1
        A: ${train.gan.discriminator.in_channels.B}
      ndf: 64
      n_layers: 2
      kernel_size:
      - 4
      - 4
      - 4
    pool_size: 50
  seed: null
  metrics:
    discriminator_evolution: true
    ssim: false
val:
  output_dir: ${train.output_dir}
  batch_size: ${train.batch_size}
  cuda: ${train.cuda}
  mixed_precision: ${train.mixed_precision}
  opt_level: ${train.opt_level}
  logging: ${train.logging}
  dataset:
    _target_: project.datasets.val_test_dataset.SynthRAD2023ValTestDataset
    root: /mnt/homeGPU/tenayat/data/VAL
    num_workers: 0
    pin_memory: true
  sliding_window:
    window_size: ${train.dataset.patch_size}
    batch_size: 1
    overlap: 0.25
    mode: gaussian
  multi_dataset: null
  freq: ${train.checkpointing.freq}
  start_after: 0
  metrics:
    ssim: true
    psnr: true
    nmse: true
    mse: true
    mae: true
    nmi: false
    histogram_chi2: false
    cycle_metrics: true
    save_to_csv: true
test:
  output_dir: ${train.output_dir}
  batch_size: ${train.batch_size}
  cuda: ${train.cuda}
  mixed_precision: ${train.mixed_precision}
  opt_level: ${train.opt_level}
  logging: ${train.logging}
  dataset:
    _target_: project.datasets.val_test_dataset.SynthRAD2023ValTestDataset
    root: /mnt/homeGPU/tenayat/data/TEST
    num_workers: 0
    pin_memory: true
  sliding_window:
    window_size: ${train.dataset.patch_size}
    batch_size: 1
    overlap: 0.25
    mode: gaussian
  multi_dataset: null
  checkpointing:
    load_iter: 0
  metrics:
    ssim: true
    psnr: true
    nmse: true
    mse: true
    mae: true
    nmi: false
    histogram_chi2: false
    compute_over_input: false
    save_to_csv: true
infer:
  output_dir: ${train.output_dir}
  batch_size: ${train.batch_size}
  cuda: ${train.cuda}
  mixed_precision: ${train.mixed_precision}
  opt_level: ${train.opt_level}
  logging: ${train.logging}
  dataset:
    _target_: project.datasets.infer_dataset.SynthRAD2023InferDataset
    root: /mnt/homeGPU/tenayat/data/TEST
    num_workers: 0
    pin_memory: true
  is_deployment: false
  sliding_window:
    window_size: ${train.dataset.patch_size}
    batch_size: 1
    overlap: 0.25
    mode: gaussian
  checkpointing:
    load_iter: 0
